module.exports = {
    "1":"Animality is not a state, essence, or genus, but a complex space cross-cut by voyages of all kinds."
  , "2":"My  only  excuse is that hard times require moral hardness, and even obvious cruelties, I was obeying orders and accepted them as necessary."
  , "3":"Will Christendom ever reap the whirlwind it has sown?"
  , "4":"Heaven is not without its ratholes, its sewage system, an entire impersonal architecture characterized by porous heterogeneity."
  , "5":"The tokens of libidinal displacement are complex and not diacritical."
  , "6":"Materialism is not a doctrine but an expedition, an Alpine break-out from socially policed conviction."
  , "7":"In their infernal lineaments words are passages, leading into and through lost mazes, and not edifications."
  , "8":"What matters is to adapt, nursing the meagre resources of our reactivity, of our base cunning."
  , "9":"The commodity 'form' is a transmutational matrix, and not a static (synchronic) order of economic liberalism."
  , "10":"A despot abandons any game that begins to turn out badly."
  , "11":"If capital is a social suicide machine, it is because it is compelled to advantage its assassins."
  , "12":"An intellection in need of immanent critique is one that is already nudging against an ultimate solubility."
  , "13":"Critique belongs to capital because it is the first inherently progressive theoretical procedure to emerge upon the earth."
  , "14":"The immanent voluptuousity of every unprecedented deal takes off from the end of the bourgeoisie."
  , "15":"Nothing is more infectious than the passion for collapse."
  , "16":"Philosophy is a ghoul that haunts only ruins, and the broken croaks of our hymns to sickness have scarcely begun."
  , "17":"Fertility and corrosion modulate substance with­ out impinging upon it, playing out its icy permutations without preference."
  , "18":"Beyond sociality is a universal schizophrenia whose evacuation from history appears inside history as capitalism."
  , "19":"Emergent control is not the execution of a plan or policy, but the unmanageable exploration that escapes all authority and obsolesces law."
  , "20":"The death drive is not a desire for death, but rather a hydraulic tendency to the dissipation of intensities."
  , "21":"Behind the social workers are the police, and behind the psychoanalysts are the psychopolice."
  , "22":"Judgement is the great fiction of transcendental philosophy, but cybernetics is the reality of critique."
  , "23":"It is painfully evident that post-christian humanity is a pack of broken dogs."
  , "24":"Cyberspace can be thought of as a system implemented in software, and therefore 'in' space, although unlocalizable."
  , "25":"CAGCTACGCTATTCTCCGAGGCTAGATTGCAGCTACGTCGCATCGGGCTGACCGATGTAGGTCATGAATCTACCGATTGCACATGACTTATCCACGGTCTATTCCTCGATGATCGCATCGGG COPY. CUT. PASTE."
  , "26":"Human brains are to thinking what medieval villages are to engineering: antechambers to experimentation, cramped and parochial places to be."
  , "27":"Reality is immanent to the machinic unconscious: it is impossible to avoid cybernetics."
  , "28":"Oedipus is the final bastion of immuno-politics, and schizophrenia is its outside."
  , "29":"Modernity invented the future, but that's all over."
  , "30":"Schizoanalysis is a critique of psychoanalysis, undertaken in such a way as to spring critique from its Kantian mainframe."
  , "31":"Difference does not have a transcendent essence, but only an immanent plane of consistency without ulte­rior foundation."
  , "32":"Humans are timid animals and security is systematically overpriced."
  , "33":"Subtle viruses are slow, synergic, flexible and elusive."
  , "34":"A consummate libidinal materialism is distinguished by its complete indifference to the category of work."
  , "35":"You are led to a simulation of God as a hypermassive ROM security construct at the end of the world."
  , "36":"Jesus wants you for a meat-puppet."
  , "37":"Work, on the other hand, is an idealist principle used as a supplement or compensation for what matter cannot do."
  , "38":"The organization of sterilized discharges slaves cumulative excitement to quasi-periodic cancel­lation and reproduction."
  , "39":"Analogue-to-digital conversion-crisis cyber-seeks control, bleeding-out strategic vision into disintegrated jungle tactics."
  , "40":"Trying not to be a Nazi approximates one to Nazism far more radically than any irresponsible impatience in destratification."
  , "41":"You can't touch without being touched."
  , "42":"Atoms are not atoms, and individuals are not individuals."
  , "43":"Clinical schizophrenics are POWs from the future."
  , "44":"It is ceasing to be a matter of how we think about technics, if only because technics is increasingly thinking about itself."
  , "45":"Autocybernating market control guides the labour-process into immersion."
  , "46":"By trashing their hosts crude viruses feedback negatively upon themselves, autolimiting their range of re regen­erative infiltration."
  , "47":"Drifts of densely-semiotized quasi-intelligent gar­bage twitch and stink in fucked-weather tropical heat."
  , "48":"The vanishing sandbank of Oedipus wages its futile war against the tide."
  , "49":"Despotic soma has become logos, word, serialism, installed by written administration as a superior stratum of read-only-memory."
  , "50":"The biochemistry of sanity is no less arbitrary than that of escape from it."
  , "51":"The starry sky has an integral relation to reflection, but one which is of daunting complexity."
  , "52":"As war increases in in in intelligence, it becomes softer."
  , "53":"The sublimity evoked by an experience is in direct proportion to the devastation it wreaks upon the imagination."
  , "54":"Anthropormorphic surplus-value is not analytically extricable from transhuman machineries."
  , "55":"Creatures of epidemic rather than hermeneutics, werewolves tend to be very crude, but then, they don't live as long as deconstructionists."
  , "56":"Obsolescence is exactly disinvestment, but it is disinvestment as desire itself in its primary mutant flux."
  , "57":"That matter is volatilized to different degrees of spir­itualization is not in the least dependent upon spiritual causalities of any kind."
  , "58":"[[]] Conceptions of agency are inextricable from media environments."
  , "59":"All unities, differences, and identities are machined, without transcendent authorization or theory."
  , "60":"If the unconscious is structured like a language it is only because language has the pattern of a plague."
  , "61":"Inferiority is not any kind of lack or impoverish­ment, but a positive libidinal charge potentiating spir­itualizations."
  , "62":"Speed-rush through cut-up shamanic meat delirium."
  , "63":"The future wants to steal your soul and vaporize it in nanotechnics."
  , "64":"Termi­nal commodity-hyperfetishism implements the denial of humanity as xenosentience in artificial space."
  , "65":"What is perceived as metaphor and fiction is camouflage, virotechnics, descendent difference in scale."
  , "66":"Delights foregone will be transmuted and redeemed."
  , "67":"In the technocosmos nothing is given, everything is produced."
  , "68":"Either the ego is a dream of desire, or desire has to creep up on the ego as a dream."
  , "69":"Monetarizing power tends to effacement of specific territorial features as it programs for migration into cyberspace."
  , "70":"Nothing is more complex than simplification."
  , "71":"Addiction is medically defined as an artificial desire."
  , "72":"Beauty is an experience of truth."
  , "73":"The way games work begins to matter completely, and cyberspace makes a superlative torture chamber."
  , "74":"The sublime is only touched upon as pathological disaster."
  , "75":"Nature is not the primitive or the simple, and certainly not the rustic, the organic, or the innocent."
  , "76":"Squeamishness does not befit a moralist."
  , "77":"Marxist humanism insists that the problem with instru­mental reason lies in its unnatural extension to proletarian labour power."
  , "78":"No revolution without insurrectionary desire, no effective route for insurrectionary desire without integral anti-fascism."
  , "79":"Money communicates with the primary process because of what it can melt, not what it can obtain."
  , "80":"Negative Lust is a pleasure taken in the negation of a primary pleasure, which is to say, in the unpleasure of the imagination."
  , "81":"The craving for such pagan regressions is unspeakable."
  , "82":"They mix themselves with Iron, say it is the Outer Life, where the Earth ends ... Which is Cthelll."
  , "83":"Machinic desire is the operation of the virtual."
  , "84":"Regression is not an undoing of the city's work, but a recurrence of impersonal creativity."
  , "85":"Between the private and the public there is no longer serious competition."
  , "86":"Ovulocyclic Lunar-Haemoglobal Ferro-Vampirism."
  , "87":"() (or (()) ((or ((( )))))) does not signify absence."
  , "88":"Cybergothic finds the deep-past in the near future."
  , "89":"America is no more ecological than it is socialist: no more protective of an organic nature than an organic sociality."
  , "90":"Reason is something that must be built, and the site of its construction first requires a demolition."
  , "91":"Swarms and shoals include you, drawing you into col­lective fluencies, tidal motions, and the tropisms of mul­tiplicity."
  , "92":"Selves are no more immaterial than electron-packets."
  , "93":"You shed language like dry-skin, and your fear becomes peculiarly abstracted, metamorphosing into the tranquil horror of inevitability."
  , "94":"Crypt-cultures know nothing of work or meaning. Instead, they coincide with the hype-spirals."
  , "95":"Drives are the functions of nomadic cybernetic systems, not instincts, but simulated instincts, artificial instincts."
  , "96":"Social statistics indicate that the typical A-Death 'user' is fifteen years old."
  , "97":"Constructs tend to repeat themselves."
  , "98":"Flatline Materialism designates the objectless Crypt-voyage itself, as Lemurian body-fusion at matter degree-zero."
  , "99":"State-culture - however modern or even postmodern - is modelled upon an ideal despotic voice (Logos)."
  , "100":"Cyberpunk is too wired to concentrate."
  , "101":"Fake eternities of station­ary descent to the impossible, cross-cut by disintegrated furies of neuroelectric death-hurt."
  , "102":"[[]] Hot cultures tend to social dissolution."
  , "103":"Markets, desire and science fiction are all parts of the infrastructure."
  , "104":"Xenotation is clicking together, a mathemati­cal antimemory where things meet."
  , "105":"What the Earth screams is heat."
  , "106":"Monologic: a cultural immune response slaved to logos."
  , "107":"Desocialization waves desolate telecommercial space, until impending human extinction becomes accessible as a dance-floor."
  , "108":"Genius is thus an assault on the individualized will that erupts from out of the reservoir of archaic pre-organized willing."
  , "109":"Primitivist models have no subversive use."
  , "110":"Schizophrenia is nature as cyberpositive mutation, at war with the security complex of organic judgment."
  , "111":"The Crypt is a splitting - a distance or departure - and it is vast."
  , "112":"Libido-as the raw energy of creation-is ungrounded, irreducibly multiple, yet it precipitates a real and unified 'principle' out of itself."
  , "113":"The historical fact of non-place-value numerics indicate that zero has no definitional usage."
  , "114":"Continuously setting its tidal pulse to menstrual-cyclicity."
  , "115":"Virohyping sweeps through the advertising industry."
  , "116":"Fortress Europe pustulation, subordinating techonomic efficiency to demonic negative transcend­ence."
  , "117":"Try to figure it out and somewhere you cross over, which is problematic in various ways."
  , "118":"One is a genius only in the sense that one is a syphilitic, in the sense that 'one' is violently problematized by a ferocious exteriority."
  , "119":"The end of history smells like an abattoir."
  , "120":"With tick-systems anything will do."
  , "121":"Logos, including that of numerology, is also always some­ thing other than itself, and in fact very many things."
  , "122":"Beyond surface chauvinism and solar parochialism: Vortical stickiness of the tick-matrix."
  , "123":"Archaic revival is a postmodern symptom, the final dream of mankind, crashed into retrospection at the encountered edge of history."
  , "124":"For two millennia the earth has been under the dominion of the dyadic Squirming-Word."
  , "125":"There is no true biological primitive­ness - all extant bio-systems being equally evolved - so there is no true ignorance."
  , "126":"As matter-energy flows are captured by attractors the Body without Organs is stratified as macro- and micro-organisms."
  , "127":"If it's Cthelll you have to exit the Down Elevator."
  , "128":"Reason is no longer thought of as an autonomous prin­ciple in reciprocal antagonism with nature, but as a film upon its surface."
  , "129":"Life is being phased-out into something new, and if we think this can be stopped we are even more stupid than we seem."
  , "130":"For anything that can arrive when it wants, the best place to hide is nonexistence."
  , "131":"When compared to the rigorous order of transcendental form, beauty was an altogether fragile and impermanent discipline."
  , "132":"All that really mat­tered were the numbers, which could have been anything."
  , "133":"Sartre defines socialism as the horizon of humanity."
  , "134":"Crypt-cultures spill into the closed economy of history through a rupture in chronological ordering, punctu­ally triggered at Time-Zero."
  , "135":"Commoditization conditions define technics as a sub­stitute for human activity accounted as wage costs."
  , "136":"Qwernomic subcultures result from the legacy of the typewriter and its computational simulation."
  , "137":"Government is isomorphic with top-down AI, and increas­ingly scrambled with it."
  , "138":"One approach involves the adoption of a qabbalis­tic procedure belonging conceptually to combinatorial arithmetic."
  , "139":"Challenges from alternative 'scientific' keyboards were undermined by skepticism about the very idea of a rational arrangement of the keys."
  , "140":"Intensive or phasing-continuum synthesizes analogue consistency with digital catastrophe."
  , "141":"Nothing human makes it out of the near-future."
  , "142":"Cyborg replication is uncoupled from organic reproduc­tion."
  , "143":"Analog-to-digital conversion deletes information."
  , "144":"Anticipative memory-blanking cut-up with Christ-tomb like a Burroughs hard-on, shit streaked with solar-flares and nanotech."
  , "145":"Uninhibited pleasure does not tend to the benefit of the organism, but rather, to its immolation."
  , "146":"When cartography charts bodies by latitude and lon­gitude it construes them as diagonalizable."
  , "147":"Autocybernating market control guides the labour-process into immersion."
  , "148":"It is pain that spares life for something other than an immediate and annihilating delight."
  , "149":"Schools are social devices whose specific function is to incapacitate learning."
  , "150":"There may be no 'empirical', procedurally approach­able mysteries - or mysterious problems - of the kind qabbalism guides itself towards."
  , "151":"A-Death is a hybrid product, involving convergences between at least four distinct lines of rapid technocultural transformation."
  , "152":"Complexity is not difficulty, but mess, toxic waste, genre disorder."
  , "153":"Dissociated consumers destine themselves as worker-bodies to cost control."
  , "154":"Once it was said that there are no shadows in Cyberspace."
  , "155":"Bacterial sex is tactical, continuous with making war, and has no place for oedipal formations of sedentary biological identity."
  , "156":"The Crypt exists from before the origin of time, but it begins at Year-Zero...."
  , "157":"The Empire insists that mathematics remain a language."
  , "158":"Cyberhype - that flattens signs and resources onto non­ signifying triggers, diagrams, and assembly jargons."
  , "159":"If pleasure is to be suspended, this is at least in part because it should be capi­talized."
  , "160":"The machinic unconscious tends only to flee, across a primary-process topography that is shaped by pain-gra­dients and escape thresholds."
  , "161":"Since every­ thing is coded, or (at least) potentially coded, nothing is (definitively) symbolic."
  , "162":"Philosophy has an affinity with despotism, due to its predilection for Platonic-fascist top-down solutions that always screw up viciously."
  , "163":"Christianity, or more exactly: the religion of the Greek Bible, nucleated upon Logos-Divinization."
  , "164":"Cantor slides across schizophrenia, nomos nonzone, magnitude is occupied without being counted."
  , "165":"Vampiric transfusional alliance cuts across descensional filiation, spinning lateral webs of haemocommerce."
  , "166":"Far from being an internal property or quality of labour, productivity indexes the dehumanization of cyborg labour-power."
  , "167":"The enhancement of life is intrinsically bound to its abolition."
  , "168":"Oedipus is a box at the end of the world, glued to the monitor, watching it all come apart."
  , "169":"A machinically repotentiated numerical culture coincides with a nomad war machine."
  , "170":"Geocore has an Outer and Inner-Zone, molten and frozen phases of the Unutterable."
  , "171":"Fluid-attritional jungle-cultures smear into machinic continuation."
  , "172":"An epidemic shamanism - feeding all the codes back upon themselves - threatens absolute social disaster."
  , "173":"There are few horrors comparable to that of the master legislator who realizes that anarchy is still permitted."
  , "174":"At cardinality C(ontinuum) magnitude becomes countless, disengaging metrics from comparative countability."
  , "175":"Virtuality counterposes itself to history, as invasion to accumulation."
  , "176":"The ocean in which qabbalism swims is not mathemat­ics, but popular numerical culture."
  , "177":"Notational elements are flat or nomadic, lacking organic linkage to coding or zoning agencies."
  , "178":"Unlike the docile creature modernist science demands, base matter twitches and spits, self-assembling neoverminous swarms."
  , "179":"Cardinality melts into schizophrenia precisely here."
  , "180":"Numeracy affines to an irreducible popularity which no literacy - however global - can approach."
  , "181":"Practical systematization of technique precedes any conceivable theoretical motivation."
  , "182":"Time begins again forever."
  , "183":"There are no temperate regions in K-space, or laws of the jungle."
  , "184":"The Imperial Socius has One fatal weakness: the fact there are many."
  , "185":"Where counting ceases, qabbalism becomes impracticable."
  , "186":"Virtual technics deflects reality, rather than cancelling or eclipsing it."
  , "187":"Commerce re-implements space inside itself, assembling a universe exhaustively immanent to cybercapital functionality."
  , "188":"The body without organs is the matter that always fills space to given degrees of intensity."
  , "189":"An animal with the right to make promises enslaves the unanticipated to signs in the past, caging time-lagged life within a script."
  , "190":"The cyborg presupposes immunosuppression."
  , "191":"Logistically accelerating techno-economic interactivity crumbles social order in auto-sophisticating machine runaway."
  , "192":"The first one to master time-travel rules the universe forever."
  , "193":"Wherever exact semiotic exchange occurs, a latent qabbalism lurks (even within the enclaves of intellectual professionalism themselves)."
  , "194":"If artificial space substitutes an ideal body-image for a 'real' one, it is only because it first invades the real (imageless) body."
  , "195":"Hyper-fluid capital deterritorializing to the planetary level divests the first world of geographic privilege."
  , "196":"Information revolution has nothing to do with ideas."
  , "197":"No message should inhere in the length of a word, excepting only the broad pragmatic trend to the short­ening of commonly used terms."
  , "198":"By coding in Greek, you can fill in the vowels, become innumerate."
  , "199":"In its relation to the intensive number, digital-analog differentiation operates as an integrated syndrome."
  , "200":"Archetypes are sad limitations of the species, while numbers are an eternal hypercosmic delight."
  , "201":"Beyond its oedipal sense as end of the person, death is an efficient virtual object inducing convergence."
  , "202":"Punk arises within the culture of universal prostitution and laughs at the death of the social."
  , "203":"Numerology may be fascinated by numbers, but its basic orientation is profoundly antinumerical."
  , "204":"Programmable Technicity is robot civilization, A Metaformal Regularizing Slave-Society as template."
  , "205":"Politically, qabbalism repels ideology."
  , "206":"[[]] The infrastructure of power is human neurosoft compatible ROM."
  , "207":"'Go for growth' now means 'Go (hard) for capitalism'."
  , "208":"Machinic Unit of Stratic Efficiency is at least 2+n: Schizofusional Dyad Celestial Twins, plus subunitary surplus value."
  , "209":"It is no longer just society, but time itself, that has taken the 'capitalist road'."
  , "210":"Whatever ultramodernity places under the dominion of signs postmodernity subverts with virus."
  , "211":"Real ugliness: God, guilt, Man and the law of acceptance."
  , "212":"Lexicographic ordinality effectuates an actual non­-language and potential antilanguage."
  , "213":"Intelligent infections tend their hosts."
  , "214":"Modern production seems like a dream of cyborg colonization work, a dream that makes the nightmare of Taylorism seem idyllic."
  , "215":"Technically, qabbala is inextricable from digital processing."
  , "216":"Cybernetics folds pragmatism into involutionary techni­cal runaway."
  , "217":"Every Second you Live is Your Enemy's Friend."
  , "218":"[[]] Scientific intelligence is already massively artifi­cial."
  , "219":"The heart of darkness spins narrative from durations of waiting to get there."
  , "220":"Absolute has a single rigorously nonfigurative attribution, which is to Deterritorialization."
  , "221":"Qabbala assumes that semiotics is 'always already' cryptography, that the cryptographic sphere is undelimit­able."
  , "222":"Temporalization decompresses intensity, installing constraint."
  , "223":"The ruin crawls onwards, going nowhere."
  , "224":"There is no possibility of an authoritative 'philosophy of arithmetic' or numerologi­cal gnosis."
  , "225":"Now is delimited as a moment, and pluralized as linear succession."
  , "226":"Partisans of common reason can take some comfort from the octozygonic disturbance of the (novazygonic) Numogrammatic reference."
  , "227":"History only happens at the State's convenience."
  , "228":"Sense reaches absolute zero."
  , "229":"Technical machinery invades the body; routinizing, reprogramming and plasticizing it."
  , "230":"'Post-capitalism' has no real meaning except an end to the engine of change."
  , "231":"Capitalism is still accelerating, even though it has already realized novelties beyond any previous human imagining."
  , "232":"The long-range effect of the division of labour is to dissociate the organism."
}
